[package]
name = "cargo-fix-example"
version = "0.1.0"
authors = ["lyoz <lyoz@users.noreply.github.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
